name: Deploy Frontend

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t kinshuk1k/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true kinshuk1k/react-test npm test
